name: Scala CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '23'
        cache: 'sbt'

    - name: Setup sbt installer
      uses: sbt/setup-sbt@v1.1.5

    - name: Run compile
      run: sbt clean compile

    - name: Cache SBT
      uses: actions/cache@v4
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

  run_tests:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Git checkout (merge)
          uses: actions/checkout@v4
          if: github.event_name != 'pull_request'
          with:
            fetch-depth: 0

        - name: Git checkout (PR)
          uses: actions/checkout@v4
          if: github.event_name == 'pull_request'
          with:
            fetch-depth: 0
            ref: ${{ github.event.pull_request.head.sha }}

        - name: Set up JDK
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '23'
            cache: 'sbt'

        - name: Setup sbt installer
          uses: sbt/setup-sbt@v1.1.5

        - name: Run tests
          run: sbt clean coverage test

        - name: Upload coverage data to Coveralls
          run: sbt coverageReport coveralls
          env:
            COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
